backend/apps/account/urls.py
from django.urls import path, include

from .views import sign_in, error

urlpatterns = [
    path("", sign_in, name="sign_in"),
    path("error/", error, name="error"),
]

backend/apps/db_password/urls.py
from django.urls import path

from backend.apps.db_password.views import addnew, edit, update, destroy, index

urlpatterns = [
    path('', index, name='index'),
    path('addnew', addnew, name='addnew'),
    path('edit/<int:id>', edit, name='edit'),
    path('update/<int:id>', update, name='update'),
    path('delete/<int:id>', destroy, name='delete'),
]

backend/config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend.apps.account.urls')),
    path('index/', include('backend.apps.db_password.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/apps/account/models.py
from django.db import models

# Create your models here.

backend/apps/db_password/models.py
from django.db import models


class Employee(models.Model):
    title = models.CharField(max_length=55, blank=True)
    login = models.CharField(max_length=255, blank=True)
    url = models.CharField(max_length=255, blank=True)
    ip_address = models.CharField(max_length=255, blank=True)
    password = models.CharField(max_length=255, blank=True)
    descriptions = models.TextField(max_length=9999, default='Примичании нет', blank=True)

    class Meta:
        db_table = "employee"

backend/apps/account/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={"class": "login", "placeholder": "Логин", }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={"class": "parol", "placeholder": "Пароль", },
    ))

backend/apps/db_password/forms.py
from django import forms

from backend.apps.db_password.models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['title', 'url', 'ip_address', 'login', 'password', 'descriptions']

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'url': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'ip_address': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'login': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'password': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'descriptions': forms.Textarea(
                attrs={
                    'class': 'form-control', 'rows': 4
                }
            ),
        }

backend/apps/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from backend.apps.account.forms import LoginForm


def sign_in(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                username=data['username'],
                password=data['password']
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('index')
                else:
                    return redirect('error')
            else:
                return redirect('error')

    else:
        form = LoginForm()

    return render(request, 'login.html', {"form": form})


def error(request):
    return render(request, 'error404.html')

backend/apps/db_password/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from backend.apps.db_password.forms import EmployeeForm
from backend.apps.db_password.models import Employee


@login_required
def addnew(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('index')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, 'password/index.html', {'form': form})


@login_required
def index(request):
    employees = Employee.objects.all()
    return render(request, "password/show.html", {'employees': employees})


@login_required
def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, 'password/edit.html', {'employee': employee})


@login_required
def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        return redirect("index")
    return render(request, 'password/edit.html', {'employee': employee})


@login_required
def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("index")

backend/apps/account/templates/error404.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple 404 Error Page</title>
    <link rel="stylesheet" href="{% static './src/css/error404.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body>
<section class="page_404">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 ">
                <div class="col-sm-10 col-sm-offset-1  text-center">
                    <div class="four_zero_four_bg">
                        <h1 class="text-center ">404</h1>


                    </div>

                    <div class="contant_box_404">
                        <h3 class="h2">
                            Look like you're lost! :)
                        </h3>

                        <p>Вы ввели не правильный логин или пароль!!!</p>

                        <a href="{% url 'sign_in' %}" class="link_404">Обратно ввести</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>

</html>

backend/apps/account/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'src/images/logo-tsvs.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static './src/css/login.css' %}">
    <title>База логина и паролей ГАРТСВС></title>
</head>
<body>
<log>
    <form action="" method="POST">
        {% csrf_token %}
        <section class="section__one">
            <div class="container">
                <div class="pasford">
                    <img src="{% static './src/images/logo_page.png' %}">
                    <div class="input">
                        {{form.username}}
                        {{form.password}}
                    </div>
                    <button class="pasford__btn">Вход</button>
                </div>
            </div>
        </section>
    </form>
</log>
</body>       

backend/apps/db_password/templates/password/edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}Редактировать{% endblock title %}

{% block content %}
<div class="col-md-12">
    <form method="POST" class="post-form" action="{% url 'update' employee.id %}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Изменить детали</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Id:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="id" id="id_id" required maxlength="255"
                           value="{{ employee.id }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Название проекта:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="title" id="id_title" maxlength="255"
                           value="{{ employee.title }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">URL проекта:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="url" id="id_url" maxlength="255"
                           value="{{ employee.url }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">IP адрес:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="ip_address" id="id_ip_address" maxlength="255"
                           value="{{ employee.ip_address }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Логин:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="login" id="id_login" maxlength="255"
                           value="{{ employee.login }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Пароль:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="password" id="id_password" maxlength="255"
                           value="{{ employee.password }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Примечание:</label>
                <div class="col-sm-4">
                    <textarea class="form-control" name="descriptions" id="id_descriptions" maxlength="255" rows="3">{{ employee.descriptions }}</textarea>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success btn-lg">Изменить</button>
                </div>
            </div>

        </div>
    </form>
    {% endblock content %}

backend/apps/db_password/templates/password/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Добавления логина и пароля{% endblock title %}

{% block content %}
<div class="col-md-12">
    <h4>Добавления логина и паролей</h4>

    <form method="POST" class="post-form" action="{% url 'addnew' %}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Заполните поля</h3>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Название проекта:</label>
                <div class="col-sm-4">
                    {{ form.title }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">URL проекта:</label>
                <div class="col-sm-4">
                    {{ form.url }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">IP адрес:</label>
                <div class="col-sm-4">
                    {{ form.ip_address }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Логин:</label>
                <div class="col-sm-4">
                    {{ form.login }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Пароль:</label>
                <div class="col-sm-4">
                    {{ form.password }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Примечание:</label>
                <div class="col-sm-4">
                    {{ form.descriptions }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">Создать</button>
                </div>
            </div>

        </div>
    </form>
</div>
{% endblock content %} 

backend/apps/db_password/templates/password/show.html
{% extends "base.html" %}
{% block title %} База логина и пароля{% endblock title %}

{% block content %}
<div class="col-md-12">
    <div class="table-responsive">
        <h1 class="text-center">Список логина и пароля</h1>
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
                <tr>
                    <th><input type="checkbox" id="checkall"/></th>
                    <th>ID</th>
                    <th style="width: 600px;">Название проекта</th>
                    <th style="width: 400px;">URL</th>
                    <th style="width: 400px;">IP</th>
                    <th style="width: 400px;">Логин</th>
                    <th style="width: 400px;">Пароль</th>
                    <th style="width: 490px;">Примечание</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td><input type="checkbox" class="checkthis"/></td>
                    <td>{{ employee.id }}</td>
                    <td style="width: 600px;">{{ employee.title }}</td>
                    <td style="width: 400px;">{{ employee.url }}</td>
                    <td style="width: 400px;">{{ employee.ip_address }}</td>
                    <td style="width: 400px;">{{ employee.login }}</td>
                    <td style="width: 400px;">{{ employee.password }}</td>
                    <td style="width: 490px;">{{ employee.descriptions }}</td>
                    <td><p data-placement="top" data-toggle="tooltip" title="Edit"><a href="{% url 'edit' employee.id %}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></span></a></p></td>
                    <td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="{% url 'delete' employee.id %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></a></p></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'src/images/logo-tsvs.png' %}" type="image/x-icon">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img alt="LOGO" src="{% static 'src/icons/logo.png' %}" width="30">
            </a>
        </div>
        <a href="{% url 'index' %}" class="btn btn-default navbar-btn btn-primary">ГЛАВНАЯ</a>
        <a href="{% url 'addnew' %}" class="btn btn-default navbar-btn btn-primary">Добавить</a>

        <div class="navbar-right p-2">
            <span class="btn btn-default navbar-btn btn-primary">{{ user.first_name }} {{ user.last_name }}</span>
            <a href="{% url 'sign_in' %}" class="btn btn-default navbar-btn btn-primary">ВЫХОД</a>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        {% block content %}{% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script src="{% static 'src/js/main.js' %}" defer></script>
</body>
</html>

backend/templates/edit.html
{% extends "base.html" %}

{% block title %}Редактировать{% endblock title %}

{% block content %}
<div class="col-md-12">
    <form method="POST" class="post-form" action="{% url 'update' employee.id %}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Изменить детали</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Id:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="id" id="id_id" required maxlength="255"
                           value="{{ employee.id }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Название проекта:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="title" id="id_title" maxlength="255"
                           value="{{ employee.title }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">URL проекта:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="url" id="id_url" maxlength="255"
                           value="{{ employee.url }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">IP адрес:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="ip_address" id="id_ip_address" maxlength="255"
                           value="{{ employee.ip_address }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Логин:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="login" id="id_login" maxlength="255"
                           value="{{ employee.login }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Пароль:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="password" id="id_password" maxlength="255"
                           value="{{ employee.password }}"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Примечание:</label>
                <div class="col-sm-4">
                    <textarea class="form-control" name="descriptions" id="id_descriptions" maxlength="255" rows="3">{{ employee.descriptions }}</textarea>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success btn-lg">Изменить</button>
                </div>
            </div>

        </div>
    </form>
    {% endblock content %}

backend/templates/index.html
{% extends "base.html" %}

{% block title %}Добавления логина и пароля{% endblock title %}

{% block content %}
<div class="col-md-12">
    <h4>Добавления логина и паролей</h4>

    <form method="POST" class="post-form" action="{% url 'addnew' %}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Заполните поля</h3>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Название проекта:</label>
                <div class="col-sm-4">
                    {{ form.title }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">URL проекта:</label>
                <div class="col-sm-4">
                    {{ form.url }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">IP адрес:</label>
                <div class="col-sm-4">
                    {{ form.ip_address }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Логин:</label>
                <div class="col-sm-4">
                    {{ form.login }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Пароль:</label>
                <div class="col-sm-4">
                    {{ form.password }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Примечание:</label>
                <div class="col-sm-4">
                    {{ form.descriptions }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">Создать</button>
                </div>
            </div>

        </div>
    </form>
</div>
{% endblock content %} 

backend/templates/show.html
{% extends "base.html" %}

{% block title %} База логина и пароля{% endblock title %}

{% block content %}
<div class="col-md-12">
    <div class="table-responsive">

        <h1 class="text-center">
            Список логина и пароля
        </h1>

        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
            <th><input type="checkbox" id="checkall"/></th>
            <th>ID</th>
            <th style="width: 600px;">Название проекта</th>
            <th style="width: 400px;">URL</th>
            <th style="width: 400px;">IP</th>
            <th style="width: 400px;">Логин</th>
            <th style="width: 400px;">Пароль</th>
            <th style="width: 490px;">Примичание</th>
            <th>Edit</th>
            <th>Delete</th>
            </thead>
            <tbody>
            {% for employee in employees %}
            <tr>
                <td><input type="checkbox" class="checkthis"/></td>
                <td>{{ employee.id }}</td>
                <td style="width: 600px;">{{ employee.title }}</td>
                <td style="width: 400px;">{{ employee.url }}</td>
                <td style="width: 400px;">{{ employee.ip_address }}</td>
                <td style="width: 400px;">{{ employee.login }}</td>
                <td style="width: 400px;">{{ employee.password }}</td>
                <td style="width: 490px;">{{ employee.descriptions }}</td>
                <td><p data-placement="top" data-toggle="tooltip" title="Edit"><a href="{% url 'edit' employee.id %}"
                                                                                  class="btn btn-primary btn-xs"
                                                                                  data-title="Edit" data-toggle="modal"
                                                                                  data-target="#edit"><span
                        class="glyphicon glyphicon-pencil"></span></a></p></td>
                <td><p data-placement="top" data-toggle="tooltip" title="Delete"><a
                        href="{% url 'delete' employee.id %}" class="btn btn-danger btn-xs" data-title="Delete"
                        data-toggle="modal" data-target="#delete"><span class="glyphicon glyphicon-trash"></span></a>
                </p></td>
            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
</div>
{% endblock content %}